<?php
session_start();
header('Content-Type: application/json; charset=utf-8');

$CONFIG     = __DIR__ . '/config.php';
$OVERRIDES  = __DIR__ . '/overrides.json';
$CONTENT_JS = dirname(__DIR__) . '/content.js';

if (file_exists($CONFIG)) require $CONFIG;
$PASS = defined('ADMIN_PASS') ? ADMIN_PASS : 'AdminPortfolio2026!';

$body   = json_decode(file_get_contents('php://input'), true) ?? [];
$action = $body['action'] ?? ($_POST['action'] ?? '');

function out($data) { echo json_encode($data, JSON_UNESCAPED_UNICODE); exit; }
function ok($x = []) { out(array_merge(['ok' => true], $x)); }
function fail($msg)  { out(['ok' => false, 'error' => $msg]); }

// ── Auth check (no session required) ─────────────────────────────────────────
if ($action === 'check') {
    ok(['authenticated' => !empty($_SESSION['ok'])]);
}

// ── All other actions require auth ────────────────────────────────────────────
if (empty($_SESSION['ok'])) fail('Not authenticated');

// ── Save overrides ────────────────────────────────────────────────────────────
if ($action === 'save') {
    $newChanges = $body['changes'] ?? [];
    if (!is_array($newChanges)) fail('Invalid payload');

    // Merge with existing overrides
    $ov = file_exists($OVERRIDES) ? (json_decode(file_get_contents($OVERRIDES), true) ?? []) : [];
    foreach ($newChanges as $key => $vals) {
        if (!is_array($vals)) continue;
        foreach (['fr', 'en'] as $lang) {
            if (isset($vals[$lang]) && $vals[$lang] !== '') {
                $ov[$key][$lang] = $vals[$lang];
            }
        }
    }

    $pretty = JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES;
    file_put_contents($OVERRIDES, json_encode($ov, $pretty));

    $js = "// Auto-generated by admin panel — " . date('Y-m-d H:i:s') . "\n"
        . "// Edit via https://tournayre.ovh/admin/\n"
        . "window.__contentOverrides = " . json_encode($ov, $pretty) . ";\n";
    file_put_contents($CONTENT_JS, $js);
    ok();
}

// ── Change password ───────────────────────────────────────────────────────────
if ($action === 'change_password') {
    $current = $body['current'] ?? '';
    $new     = $body['new']     ?? '';
    $confirm = $body['confirm'] ?? '';

    if (!hash_equals(hash('sha256', $PASS), hash('sha256', $current)))
        fail('Mot de passe actuel incorrect');
    if (strlen($new) < 8)
        fail('Le nouveau mot de passe doit contenir au moins 8 caractères');
    if ($new !== $confirm)
        fail('Les mots de passe ne correspondent pas');

    $safe = addslashes($new);
    $php  = "<?php\n// Admin panel password — do NOT commit this file to git\ndefine('ADMIN_PASS', '$safe');\n";
    if (file_put_contents($CONFIG, $php) === false) fail('Impossible d\'écrire config.php');
    ok(['message' => 'Mot de passe mis à jour']);
}

fail('Action inconnue');
