<?php
session_start();

// ─── Config ───────────────────────────────────────────────────────────────────
$CONFIG       = __DIR__ . '/config.php';
$OVERRIDES    = __DIR__ . '/overrides.json';
$CONTENT_JS   = dirname(__DIR__) . '/content.js';
$DEFAULT_PASS = 'AdminPortfolio2026!'; // fallback — override in config.php

if (file_exists($CONFIG)) require $CONFIG;
$PASS = defined('ADMIN_PASS') ? ADMIN_PASS : $DEFAULT_PASS;

// ─── Actions ──────────────────────────────────────────────────────────────────
$action = $_POST['action'] ?? $_GET['action'] ?? '';
$flash  = '';

if ($action === 'logout') {
    session_destroy();
    header('Location: /admin/');
    exit;
}

if ($action === 'login' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    if (hash_equals(hash('sha256', $PASS), hash('sha256', trim($_POST['pass'] ?? '')))) {
        $_SESSION['ok'] = true;
        header('Location: /admin/');
        exit;
    }
    $flash = 'error';
}

if ($action === 'save' && isset($_SESSION['ok']) && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $keys = [
        'meta.description', 'meta.og.description',
        'hero.title', 'hero.desc', 'hero.cta', 'hero.cv',
        'about.text', 'contact.text',
    ];
    $ov = [];
    foreach ($keys as $k) {
        $safe = str_replace(['.', '-'], '_', $k);
        $fr   = trim($_POST['fr_' . $safe] ?? '');
        $en   = trim($_POST['en_' . $safe] ?? '');
        if ($fr !== '' || $en !== '') {
            if ($fr !== '') $ov[$k]['fr'] = $fr;
            if ($en !== '') $ov[$k]['en'] = $en;
        }
    }
    file_put_contents($OVERRIDES, json_encode($ov, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
    $js  = "// Auto-generated by admin panel — " . date('Y-m-d H:i:s') . "\n";
    $js .= "// Edit at https://tournayre.ovh/admin/\n";
    $js .= "window.__contentOverrides = " . json_encode($ov, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . ";\n";
    file_put_contents($CONTENT_JS, $js);
    $flash = 'saved';
}

// ─── Load overrides ───────────────────────────────────────────────────────────
$ov = file_exists($OVERRIDES) ? (json_decode(file_get_contents($OVERRIDES), true) ?? []) : [];

function ov($ov, $k, $l) { return htmlspecialchars($ov[$k][$l] ?? '', ENT_QUOTES); }
function field($ov, $k, $label, $multiline = true) {
    $safe = str_replace(['.', '-'], '_', $k);
    $fr   = ov($ov, $k, 'fr');
    $en   = ov($ov, $k, 'en');
    $tag  = $multiline ? 'textarea' : 'input type="text"';
    $close = $multiline ? '</textarea>' : '';
    $rows = $multiline ? ' rows="3"' : '';
    echo "<div class='field'>";
    echo "<div class='field-label'>$label <code>$k</code></div>";
    echo "<div class='langs'>";
    echo "<label>🇫🇷 FR<$tag name='fr_{$safe}' class='tx'{$rows} placeholder='(default i18n.js value)'>{$fr}{$close}</label>";
    echo "<label>🇬🇧 EN<$tag name='en_{$safe}' class='tx'{$rows} placeholder='(default i18n.js value)'>{$en}{$close}</label>";
    echo "</div></div>";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Content Editor — tournayre.ovh</title>
<meta name="robots" content="noindex,nofollow">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
*{margin:0;padding:0;box-sizing:border-box}
:root{
  --accent:#ff8c42;--accent-d:rgba(255,140,66,.1);
  --bg:#0a0a0c;--surface:rgba(255,255,255,.04);
  --border:rgba(255,255,255,.09);--text:#eaeaec;
  --muted:rgba(255,255,255,.45);--green:#36d399;--red:#ff6b6b;
  --radius:10px;
}
body{background:var(--bg);color:var(--text);font-family:Inter,-apple-system,sans-serif;font-size:14px;min-height:100vh}

/* ── Login ── */
.login-wrap{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1rem}
.login-box{
  background:var(--surface);border:1px solid var(--border);border-radius:16px;
  padding:2.5rem 2rem;width:100%;max-width:360px;text-align:center;
}
.login-box h1{font-size:1.25rem;font-weight:700;margin-bottom:.25rem}
.login-box p{color:var(--muted);font-size:.83rem;margin-bottom:2rem}
.login-box input{
  width:100%;padding:.75rem 1rem;background:rgba(255,255,255,.06);
  border:1px solid var(--border);border-radius:8px;color:var(--text);
  font-size:.9rem;outline:none;margin-bottom:1rem;
  transition:border-color .2s;
}
.login-box input:focus{border-color:rgba(255,140,66,.4)}
.login-box button{
  width:100%;padding:.75rem;background:var(--accent-d);color:var(--accent);
  border:1px solid rgba(255,140,66,.3);border-radius:8px;font-size:.9rem;
  font-weight:600;cursor:pointer;transition:all .2s;
}
.login-box button:hover{background:rgba(255,140,66,.18);border-color:rgba(255,140,66,.55)}
.err-msg{color:var(--red);font-size:.8rem;margin-top:.75rem}

/* ── Layout ── */
.topbar{
  position:sticky;top:0;z-index:50;
  background:rgba(10,10,12,.92);border-bottom:1px solid var(--border);
  backdrop-filter:blur(12px);
  display:flex;align-items:center;gap:1rem;padding:.7rem 2rem;
}
.topbar-logo{font-weight:700;color:var(--accent);font-size:.9rem;letter-spacing:.04em}
.topbar-logo span{color:var(--muted);font-weight:400}
.spacer{flex:1}
.btn{
  display:inline-flex;align-items:center;gap:.4rem;
  padding:.45rem 1rem;border-radius:7px;font-size:.8rem;font-weight:600;
  cursor:pointer;text-decoration:none;border:1px solid var(--border);
  background:transparent;color:var(--muted);transition:all .2s;
}
.btn:hover{border-color:rgba(255,255,255,.2);color:var(--text)}
.btn.primary{
  background:var(--accent-d);color:var(--accent);
  border-color:rgba(255,140,66,.3);
}
.btn.primary:hover{background:rgba(255,140,66,.18);border-color:rgba(255,140,66,.55)}

.main{max-width:900px;margin:0 auto;padding:2rem 1.5rem}

/* ── Flash ── */
.flash{
  padding:.75rem 1.1rem;border-radius:8px;margin-bottom:1.5rem;font-size:.84rem;
}
.flash.saved{background:rgba(54,211,153,.1);border:1px solid rgba(54,211,153,.25);color:var(--green)}
.flash.error{background:rgba(255,107,107,.1);border:1px solid rgba(255,107,107,.25);color:var(--red)}

/* ── Sections ── */
.section{margin-bottom:2rem}
.section-title{
  font-size:.68rem;font-weight:700;letter-spacing:.12em;
  text-transform:uppercase;color:var(--accent);
  border-bottom:1px solid var(--border);padding-bottom:.6rem;margin-bottom:1.2rem;
}
.field{
  background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);
  padding:1rem 1.1rem;margin-bottom:.85rem;
}
.field-label{
  font-size:.75rem;font-weight:600;color:var(--text);
  margin-bottom:.75rem;display:flex;align-items:center;gap:.6rem;flex-wrap:wrap;
}
.field-label code{
  background:rgba(255,255,255,.06);padding:.15rem .45rem;
  border-radius:4px;font-size:.7rem;color:var(--muted);letter-spacing:.03em;
}
.langs{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}
.langs label{display:flex;flex-direction:column;gap:.35rem;font-size:.72rem;color:var(--muted)}
.tx{
  width:100%;background:rgba(255,255,255,.06);border:1px solid var(--border);
  border-radius:7px;color:var(--text);font-size:.8rem;font-family:inherit;
  padding:.55rem .75rem;outline:none;resize:vertical;transition:border-color .2s;
}
.tx:focus{border-color:rgba(255,140,66,.38)}
.tx::placeholder{color:rgba(255,255,255,.2);font-style:italic}

/* ── Footer ── */
.footer{text-align:center;color:var(--muted);font-size:.72rem;padding:2rem 0;border-top:1px solid var(--border);margin-top:2rem}

@media(max-width:560px){.langs{grid-template-columns:1fr}}
</style>
</head>
<body>
<?php if (!isset($_SESSION['ok'])): ?>
<!-- ── Login ── -->
<div class="login-wrap">
  <div class="login-box">
    <h1>Content Editor</h1>
    <p>tournayre.ovh — admin panel</p>
    <form method="post">
      <input type="hidden" name="action" value="login">
      <input type="password" name="pass" placeholder="Password" autofocus>
      <button type="submit">Sign in</button>
      <?php if ($flash === 'error'): ?><div class="err-msg">Incorrect password.</div><?php endif ?>
    </form>
  </div>
</div>

<?php else: ?>
<!-- ── Editor ── -->
<div class="topbar">
  <div class="topbar-logo">tournayre.ovh <span>/ content editor</span></div>
  <div class="spacer"></div>
  <a href="/" target="_blank" class="btn">↗ Preview site</a>
  <a href="?action=logout" class="btn">Logout</a>
  <button type="submit" form="editForm" class="btn primary">✓ Save &amp; publish</button>
</div>

<div class="main">
  <?php if ($flash === 'saved'): ?>
  <div class="flash saved">✓ Saved &mdash; content.js updated. Changes are live.</div>
  <?php endif ?>

  <form method="post" id="editForm">
    <input type="hidden" name="action" value="save">

    <div class="section">
      <div class="section-title">SEO &amp; Meta</div>
      <?php field($ov, 'meta.description',    'Meta description (Google snippet)') ?>
      <?php field($ov, 'meta.og.description', 'Open Graph description (social share)') ?>
    </div>

    <div class="section">
      <div class="section-title">Hero — section d'accueil</div>
      <?php field($ov, 'hero.title', 'Title (HTML allowed: &lt;span&gt;)') ?>
      <?php field($ov, 'hero.desc',  'Subtitle / tagline') ?>
      <?php field($ov, 'hero.cta',   'Primary CTA button', false) ?>
      <?php field($ov, 'hero.cv',    'Secondary CTA button', false) ?>
    </div>

    <div class="section">
      <div class="section-title">About / Profile</div>
      <?php field($ov, 'about.text', 'Profile paragraph') ?>
    </div>

    <div class="section">
      <div class="section-title">Contact</div>
      <?php field($ov, 'contact.text', 'Contact section text', false) ?>
    </div>
  </form>

  <p style="font-size:.72rem;color:var(--muted);margin-top:-.5rem">
    Empty fields keep the default value from <code style="color:rgba(255,255,255,.4)">i18n.js</code>.
    Only overrides are written to <code style="color:rgba(255,255,255,.4)">content.js</code>.
  </p>
</div>

<div class="footer">
  Content Editor — tournayre.ovh &mdash;
  <a href="/" style="color:var(--muted);text-decoration:none" target="_blank">Open site ↗</a>
</div>
<?php endif ?>
</body>
</html>
